name: Bug Report
description: Report a bug or issue with the ML platform
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the ML platform is affected?
      options:
        - EKS Cluster
        - Model Registry
        - Feature Store
        - CI/CD Pipeline
        - Observability/Monitoring
        - Infrastructure (Terraform)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy to EKS...
        2. Run command...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected result...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actual result...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Relevant logs, error messages, or stack traces
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      value: |
        - EKS Version:
        - Kubernetes Version:
        - AWS Region:
        - Terraform Version:
        - Other tools:
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Add context, screenshots, or related issues...
