name: Feature Request
description: Suggest a new feature or enhancement for the ML platform
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the platform would this feature affect?
      options:
        - EKS Cluster
        - Model Registry
        - Feature Store
        - CI/CD Pipeline
        - Observability/Monitoring
        - Infrastructure (Terraform)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm trying to... but currently..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "I think we should..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: "Alternatively, we could..."

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this feature?
      placeholder: |
        - Improved performance
        - Better user experience
        - Cost reduction
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any thoughts on how to implement this?
      placeholder: "Could be implemented using..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocking work)
        - High (important for project success)
        - Medium (nice to have)
        - Low (future consideration)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Links, references, or examples...
