apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-platform-resource-quotas
  namespace: argocd
spec:
  project: ml-platform-dev
  source:
    repoURL: 'https://github.com/wlevan3/ml-platform-engineering-practicum'
    targetRevision: HEAD
    path: clusters/dev/bootstrap/k8s-manifests/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ml-platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
