#!/usr/bin/env python3
"""
Generate a Sentinel mock module from a Terraform plan in JSON format.

This produces a Sentinel file that exports a minimal subset of the tfplan/v2
import surface required by our policies (currently, resource_changes with
change.actions/after payloads). The generated mock is consumed by the
Sentinel CLI during `sentinel apply` via the configuration in
`policy/sentinel/dev.hcl`.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict


def build_resource_changes(plan: Dict[str, Any]) -> Dict[str, Any]:
    """Convert Terraform plan resource changes into a map keyed by address."""
    changes = {}
    for rc in plan.get("resource_changes", []):
        address = rc.get("address")
        if not address:
            continue

        change_block = rc.get("change", {})
        change = {
            # Sentinel only needs the action list and the after-state for our policy.
            "actions": change_block.get("actions", []),
            "after": change_block.get("after"),
        }

        changes[address] = {
            "type": rc.get("type"),
            "mode": rc.get("mode"),
            "change": change,
        }
    return changes


def format_sentinel_map(data: Dict[str, Any]) -> str:
    """Render a Python dict as single-line JSON compatible with Sentinel."""
    return json.dumps(data, separators=(",", ":"), sort_keys=True)


def generate_mock(plan_path: Path, output_path: Path) -> None:
    plan = json.loads(plan_path.read_text())
    resource_changes = build_resource_changes(plan)

    sentinel_body = (
        "// Generated by scripts/generate_sentinel_tfplan_mock.py; do not edit manually.\n"
        "resource_changes = "
        f"{format_sentinel_map(resource_changes)}\n"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(sentinel_body)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Sentinel mock module from Terraform plan JSON."
    )
    parser.add_argument(
        "--plan",
        type=Path,
        default=Path("terraform/environments/dev/plan.json"),
        help="Path to the Terraform plan JSON (default: %(default)s)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("policy/sentinel/mocks/dev-plan.sentinel"),
        help="Output Sentinel mock file (default: %(default)s)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    generate_mock(args.plan, args.output)


if __name__ == "__main__":
    main()
