#!/usr/bin/env python3
"""
Generate a Sentinel mock module from a Terraform plan in JSON format.

This produces a Sentinel file that exports a minimal subset of the tfplan/v2
import surface required by our policies (currently, resource_changes with
change.actions/after payloads). The generated mock is consumed by the
Sentinel CLI during `sentinel apply` via the configuration in
`infra/policies/sentinel/dev.hcl`.
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def build_resource_changes(plan: dict[str, Any]) -> dict[str, Any]:
    """Convert Terraform plan resource changes into a map keyed by address."""
    changes = {}
    skipped = 0
    for rc in plan.get("resource_changes", []):
        address = rc.get("address")
        if not address:
            skipped += 1
            continue

        change_block = rc.get("change", {})
        change = {
            # Sentinel only needs the action list and the after-state for our policy.
            "actions": change_block.get("actions", []),
            "after": change_block.get("after"),
        }

        changes[address] = {
            "type": rc.get("type"),
            "mode": rc.get("mode"),
            "change": change,
        }
    if skipped:
        logger.warning("Skipped %s resource change(s) without an address", skipped)
    return changes


def format_sentinel_map(data: dict[str, Any]) -> str:
    """Render a Python dict as single-line JSON compatible with Sentinel."""
    return json.dumps(data, separators=(",", ":"), sort_keys=True)


def generate_mock(plan_path: Path, output_path: Path) -> None:
    try:
        plan_text = plan_path.read_text()
    except FileNotFoundError as exc:
        raise SystemExit(f"Error: Plan file not found: {plan_path}") from exc
    except PermissionError as exc:
        raise SystemExit(f"Error: Permission denied reading: {plan_path}") from exc

    try:
        plan = json.loads(plan_text)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Error: Invalid JSON in plan file: {exc}") from exc

    resource_changes = build_resource_changes(plan)

    sentinel_body = (
        "// Generated by scripts/generate_sentinel_tfplan_mock.py; do not edit manually.\n"
        "resource_changes = "
        f"{format_sentinel_map(resource_changes)}\n"
    )

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(sentinel_body)
    except (PermissionError, OSError) as exc:
        raise SystemExit(f"Error writing output file {output_path}: {exc}") from exc

    logger.info("Generated Sentinel tfplan mock: %s", output_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Sentinel mock module from Terraform plan JSON."
    )
    parser.add_argument(
        "--plan",
        type=Path,
        default=Path("infra/aws-core/terraform/environments/dev/plan.json"),
        help="Path to the Terraform plan JSON (default: %(default)s)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("infra/policies/sentinel/mocks/dev-plan.sentinel"),
        help="Output Sentinel mock file (default: %(default)s)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    generate_mock(args.plan, args.output)


if __name__ == "__main__":
    main()
